"""setting a unique rule for variable, projection, location in data_mapping table 250725

Revision ID: 1058431ef02c
Revises: 60d9f94d5376
Create Date: 2025-07-25 17:38:04.067381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1058431ef02c'
down_revision: Union[str, Sequence[str], None] = '60d9f94d5376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_loc_var_proj', 'data_mapping', ['location_id', 'variable_id', 'projection_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_loc_var_proj', 'data_mapping', type_='unique')
    # ### end Alembic commands ###
