"""locations, variables, mapping_data tables

Revision ID: 1bbe81f67bfd
Revises: b0062b10d827
Create Date: 2025-07-22 12:33:43.708295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bbe81f67bfd'
down_revision: Union[str, Sequence[str], None] = 'b0062b10d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('idx_coordinates'), table_name='variables_metadata')
    op.drop_table('variables_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables_metadata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('global_model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('regional_model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('rcp_scenario', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('variable', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ensemble', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_coordinates'), 'variables_metadata', ['longitude', 'latitude'], unique=False)
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aws_user_name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('account_type', mysql.ENUM('commercial', 'academic', 'beta', 'alpha'), nullable=False),
    sa.Column('subscription_expires_in', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
