"""Add new tables davis__sensor_catalog davis_data_structures

Revision ID: 2d99cb359a13
Revises: 
Create Date: 2025-03-28 21:16:10.391820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d99cb359a13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('davis_data_structures',
    sa.Column('data_structure_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('data_structure', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('data_structure_type')
    )
    op.create_table('davis_sensor_catalog',
    sa.Column('sensor_type', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_number', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('data_structures', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_type')
    )
    op.alter_column('davis_weather_stations', 'firmware_version',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('davis_weather_stations', 'firmware_version',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_table('davis_sensor_catalog')
    op.drop_table('davis_data_structures')
    # ### end Alembic commands ###
