"""switching starting and ending date to nullable 250723

Revision ID: 38e04de22f55
Revises: 7c37fe62ff80
Create Date: 2025-07-23 13:55:06.673904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38e04de22f55'
down_revision: Union[str, Sequence[str], None] = '7c37fe62ff80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False, postgresql_using='gist')
    op.alter_column('projection_attributes', 'starting_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('projection_attributes', 'ending_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projection_attributes', 'ending_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('projection_attributes', 'starting_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('idx_locations_geom', table_name='locations', postgresql_using='gist')
    # ### end Alembic commands ###
