"""Add confirmation_status columnn to Users table 250730

Revision ID: 42cd0728e98f
Revises: dae61d092b98
Create Date: 2025-07-30 20:56:45.736197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42cd0728e98f'
down_revision: Union[str, Sequence[str], None] = 'dae61d092b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'data_mapping', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'data_mapping', 'projection_attributes', ['projection_id'], ['id'])
    op.add_column('users', sa.Column('confirmation_status', sa.Enum('confirmed', 'unconfirmed', name='confirmationstatus'), nullable=False))
    op.create_unique_constraint(None, 'variables', ['standard_name'])
    op.drop_column('variables', 'projection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('projection_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'variables', type_='unique')
    op.drop_column('users', 'confirmation_status')
    op.drop_constraint(None, 'data_mapping', type_='foreignkey')
    op.drop_constraint(None, 'data_mapping', type_='foreignkey')
    # ### end Alembic commands ###
