"""set elevation to NULL 250724

Revision ID: 60d9f94d5376
Revises: 38e04de22f55
Create Date: 2025-07-24 11:25:16.393286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60d9f94d5376'
down_revision: Union[str, Sequence[str], None] = '38e04de22f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'elevation',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'elevation',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
