"""Alter table name Add new column

Revision ID: 866374582c79
Revises: 2d99cb359a13
Create Date: 2025-07-01 00:01:55.861912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '866374582c79'
down_revision: Union[str, Sequence[str], None] = '2d99cb359a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('code'), table_name='adcon_rtus')
    op.drop_index(op.f('name'), table_name='adcon_rtus')
    op.drop_index(op.f('serial'), table_name='adcon_rtus')
    op.drop_index(op.f('source_id'), table_name='adcon_rtus')
    op.drop_table('adcon_rtus')
    op.drop_table('davis_data_structures')
    op.drop_table('farms_registry')
    op.drop_index(op.f('device_id'), table_name='davis_weather_stations')
    op.drop_index(op.f('gateway_id'), table_name='davis_weather_stations')
    op.drop_index(op.f('gateway_id_hex'), table_name='davis_weather_stations')
    op.drop_index(op.f('station_id_uuid'), table_name='davis_weather_stations')
    op.drop_index(op.f('station_name'), table_name='davis_weather_stations')
    op.drop_table('davis_weather_stations')
    op.drop_index(op.f('key_id'), table_name='metrica_api_credentials')
    op.drop_index(op.f('secret_name'), table_name='metrica_api_credentials')
    op.drop_index(op.f('station_id'), table_name='metrica_api_credentials')
    op.drop_table('metrica_api_credentials')
    op.drop_table('IoTdevices')
    op.drop_table('fields_registry')
    op.drop_index(op.f('title'), table_name='metrica_monitoring_devices')
    op.drop_table('metrica_monitoring_devices')
    op.drop_index(op.f('device_id'), table_name='metrica_stations')
    op.drop_index(op.f('station_code'), table_name='metrica_stations')
    op.drop_index(op.f('title'), table_name='metrica_stations')
    op.drop_table('metrica_stations')
    op.drop_index(op.f('code'), table_name='adcon_servers')
    op.drop_index(op.f('name'), table_name='adcon_servers')
    op.drop_index(op.f('serial'), table_name='adcon_servers')
    op.drop_index(op.f('source_id'), table_name='adcon_servers')
    op.drop_table('adcon_servers')
    op.drop_index(op.f('name'), table_name='adcon_area')
    op.drop_index(op.f('server_id'), table_name='adcon_area')
    op.drop_index(op.f('source_id'), table_name='adcon_area')
    op.drop_table('adcon_area')
    op.drop_table('davis_monitoring_devices')
    op.drop_index(op.f('key_id'), table_name='adcon_api_credentials')
    op.drop_index(op.f('secret_name'), table_name='adcon_api_credentials')
    op.drop_index(op.f('station_id'), table_name='adcon_api_credentials')
    op.drop_table('adcon_api_credentials')
    op.drop_index(op.f('key_id'), table_name='davis_api_credentials')
    op.drop_index(op.f('secret_name'), table_name='davis_api_credentials')
    op.drop_index(op.f('station_id'), table_name='davis_api_credentials')
    op.drop_table('davis_api_credentials')
    op.drop_table('applications_registry')
    op.drop_table('advices_registry')
    op.drop_index(op.f('name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('source_id'), table_name='adcon_monitoring_control_devices')
    op.drop_index(op.f('template'), table_name='adcon_monitoring_control_devices')
    op.drop_table('adcon_monitoring_control_devices')
    op.drop_table('davis_sensor_catalog')
    op.drop_table('users_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aws_user_name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('account_type', mysql.ENUM('commercial', 'academic', 'beta', 'alpha'), nullable=False),
    sa.Column('subscription_expires_in', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('davis_sensor_catalog',
    sa.Column('sensor_type', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('product_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('data_structures', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_type'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('adcon_monitoring_control_devices',
    sa.Column('monitoring_device_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rtu_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('measurement', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('template', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('main_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sub_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('EUID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sampling_method', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('reference_offset', mysql.FLOAT(), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rtu_id'], ['adcon_rtus.rtu_id'], name=op.f('adcon_monitoring_control_devices_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitoring_device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('template'), 'adcon_monitoring_control_devices', ['template'], unique=True)
    op.create_index(op.f('source_id'), 'adcon_monitoring_control_devices', ['source_id'], unique=True)
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('api_url', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('api_version', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('templates', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'manufacturers', ['name'], unique=True)
    op.create_table('advices_registry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('irrigation', 'fertigation', 'fertilization'), nullable=False),
    sa.Column('status', mysql.ENUM('completed', 'in_process', 'canceled'), nullable=False),
    sa.Column('date_registered', mysql.FLOAT(), nullable=False),
    sa.Column('date_created', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields_registry.field_id'], name=op.f('advices_registry_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applications_registry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('irrigation', 'fertigation', 'fertilization'), nullable=False),
    sa.Column('suggested_amount', mysql.FLOAT(), nullable=False),
    sa.Column('applied_amount', mysql.FLOAT(), nullable=False),
    sa.Column('applied_in', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields_registry.field_id'], name=op.f('applications_registry_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('davis_api_credentials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_id', mysql.VARCHAR(length=767), nullable=False),
    sa.Column('secret_name', mysql.VARCHAR(length=767), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['IoTdevices.device_id'], name=op.f('davis_api_credentials_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('station_id'), 'davis_api_credentials', ['station_id'], unique=True)
    op.create_index(op.f('secret_name'), 'davis_api_credentials', ['secret_name'], unique=True)
    op.create_index(op.f('key_id'), 'davis_api_credentials', ['key_id'], unique=True)
    op.create_table('adcon_api_credentials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_id', mysql.VARCHAR(length=767), nullable=False),
    sa.Column('secret_name', mysql.VARCHAR(length=767), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['IoTdevices.device_id'], name=op.f('adcon_api_credentials_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('station_id'), 'adcon_api_credentials', ['station_id'], unique=True)
    op.create_index(op.f('secret_name'), 'adcon_api_credentials', ['secret_name'], unique=True)
    op.create_index(op.f('key_id'), 'adcon_api_credentials', ['key_id'], unique=True)
    op.create_table('davis_monitoring_devices',
    sa.Column('monitoring_device_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id_uuid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('measurement', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('modified_date', mysql.DATETIME(), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('elevation', mysql.FLOAT(), nullable=False),
    sa.Column('reference_offset', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['davis_weather_stations.station_id'], name=op.f('davis_monitoring_devices_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id_uuid'], ['davis_weather_stations.station_id_uuid'], name=op.f('davis_monitoring_devices_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitoring_device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('adcon_area',
    sa.Column('area_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('server_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('template', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('main_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sub_class', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['adcon_servers.server_id'], name='adcon_area_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('source_id'), 'adcon_area', ['source_id'], unique=True)
    op.create_index(op.f('server_id'), 'adcon_area', ['server_id'], unique=True)
    op.create_index(op.f('name'), 'adcon_area', ['name'], unique=True)
    op.create_table('adcon_servers',
    sa.Column('server_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('template', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('main_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sub_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('serial', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('time_zone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=False),
    sa.Column('slot_interval', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('get_data_max_slots', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('get_data_max_nodes', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['IoTdevices.device_id'], name='adcon_servers_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('source_id'), 'adcon_servers', ['source_id'], unique=True)
    op.create_index(op.f('serial'), 'adcon_servers', ['serial'], unique=True)
    op.create_index(op.f('name'), 'adcon_servers', ['name'], unique=True)
    op.create_index(op.f('code'), 'adcon_servers', ['code'], unique=True)
    op.create_table('metrica_stations',
    sa.Column('station_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('elevation', mysql.FLOAT(), nullable=False),
    sa.Column('farm_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_ids', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['IoTdevices.device_id'], name='metrica_stations_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms_registry.farm_id'], name='metrica_stations_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('station_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('title'), 'metrica_stations', ['title'], unique=True)
    op.create_index(op.f('station_code'), 'metrica_stations', ['station_code'], unique=True)
    op.create_index(op.f('device_id'), 'metrica_stations', ['device_id'], unique=True)
    op.create_table('metrica_monitoring_devices',
    sa.Column('monitoring_device_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('station_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('station_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('measurement', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_sensor_of_station', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sensor_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('elevation', mysql.FLOAT(), nullable=False),
    sa.Column('reference_offset', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['station_code'], ['metrica_stations.station_code'], name=op.f('metrica_monitoring_devices_ibfk_2')),
    sa.ForeignKeyConstraint(['station_id'], ['metrica_stations.station_id'], name=op.f('metrica_monitoring_devices_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitoring_device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('title'), 'metrica_monitoring_devices', ['title'], unique=True)
    op.create_table('fields_registry',
    sa.Column('field_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('boundaries', mysql.JSON(), nullable=False),
    sa.Column('soil_properties', mysql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms_registry.farm_id'], name='fields_registry_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('IoTdevices',
    sa.Column('device_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('access', mysql.JSON(), nullable=False),
    sa.Column('icon_type', mysql.ENUM('meteo', 'coastal', 'inland', 'soil'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], name='IoTdevices_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('metrica_api_credentials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_id', mysql.VARCHAR(length=767), nullable=False),
    sa.Column('secret_name', mysql.VARCHAR(length=767), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['IoTdevices.device_id'], name=op.f('metrica_api_credentials_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('station_id'), 'metrica_api_credentials', ['station_id'], unique=True)
    op.create_index(op.f('secret_name'), 'metrica_api_credentials', ['secret_name'], unique=True)
    op.create_index(op.f('key_id'), 'metrica_api_credentials', ['key_id'], unique=True)
    op.create_table('davis_weather_stations',
    sa.Column('station_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id_uuid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('station_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('gateway_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gateway_id_hex', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('product_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('recording_interval', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firmware_version', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('registered_date', mysql.DATETIME(), nullable=False),
    sa.Column('subscription_end_date', mysql.DATETIME(), nullable=False),
    sa.Column('time_zone', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('elevation', mysql.FLOAT(), nullable=False),
    sa.Column('gateway_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('farm_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_ids', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['IoTdevices.device_id'], name=op.f('davis_weather_stations_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms_registry.farm_id'], name=op.f('davis_weather_stations_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('station_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('station_name'), 'davis_weather_stations', ['station_name'], unique=True)
    op.create_index(op.f('station_id_uuid'), 'davis_weather_stations', ['station_id_uuid'], unique=True)
    op.create_index(op.f('gateway_id_hex'), 'davis_weather_stations', ['gateway_id_hex'], unique=True)
    op.create_index(op.f('gateway_id'), 'davis_weather_stations', ['gateway_id'], unique=True)
    op.create_index(op.f('device_id'), 'davis_weather_stations', ['device_id'], unique=True)
    op.create_table('farms_registry',
    sa.Column('farm_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.user_id'], name='farms_registry_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('farm_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('davis_data_structures',
    sa.Column('data_structure_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('data_structure', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('data_structure_type'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('adcon_rtus',
    sa.Column('rtu_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('template', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('main_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sub_class', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('serial', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('time_zone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date', mysql.FLOAT(), nullable=False),
    sa.Column('uptime', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('first_slot', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_slot', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('altitude', mysql.FLOAT(), nullable=False),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['adcon_area.area_id'], name=op.f('adcon_rtus_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields_registry.field_id'], name=op.f('adcon_rtus_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rtu_id'], ['IoTdevices.device_id'], name=op.f('adcon_rtus_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rtu_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('source_id'), 'adcon_rtus', ['source_id'], unique=True)
    op.create_index(op.f('serial'), 'adcon_rtus', ['serial'], unique=True)
    op.create_index(op.f('name'), 'adcon_rtus', ['name'], unique=True)
    op.create_index(op.f('code'), 'adcon_rtus', ['code'], unique=True)
    # ### end Alembic commands ###
