"""Adding data_products table

Revision ID: dae61d092b98
Revises: 1058431ef02c
Create Date: 2025-07-28 11:21:24.705803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dae61d092b98'
down_revision: Union[str, Sequence[str], None] = '1058431ef02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('aggregation_function', sa.Enum('daily_mean', 'daily_max', 'daily_min', 'daily_median', 'hourly_mean', 'hourly_max', 'hourly_min', 'hourly_median', name='aggregationfunction'), nullable=False),
    sa.Column('termporal_resolution', sa.Enum('annual', 'monthly', 'daily', 'hourly', 'half_hour', 'quarter_hour', name='temporalresolution'), nullable=False),
    sa.Column('spatial_resolution', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('data_mapping', sa.Column('data_product_id', sa.Integer(), nullable=False))
    # op.create_unique_constraint('uq_proj_loc_dp', 'data_mapping', ['projection_id', 'location_id', 'data_product_id'])
    op.create_foreign_key(None, 'data_mapping', 'data_products', ['data_product_id'], ['id'])
    # op.drop_column('data_mapping', 'variable_id')
    # op.drop_constraint(op.f('variables_ibfk_1'), 'variables', type_='foreignkey')
    # op.drop_column('variables', 'projection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('projection_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('variables_ibfk_1'), 'variables', 'projection_attributes', ['projection_id'], ['id'])
    op.create_index(op.f('uq_standardName_projectionID'), 'variables', ['projection_id', 'standard_name'], unique=True)
    op.add_column('data_mapping', sa.Column('variable_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'data_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('data_mapping_ibfk_3'), 'data_mapping', 'variables', ['variable_id'], ['id'])
    op.drop_constraint('uq_proj_loc_dp', 'data_mapping', type_='unique')
    op.create_index(op.f('uq_loc_var_proj'), 'data_mapping', ['location_id', 'variable_id', 'projection_id'], unique=True)
    op.drop_column('data_mapping', 'data_product_id')
    op.drop_table('data_products')
    # ### end Alembic commands ###
